name: Bicep Template Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc:
    runs-on: windows-latest
    environment: OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Bicep Template Repo
        uses: actions/checkout@v4
        with:
          repository: BicepTempate
          ref: main
          path: bicep-template
          token: ${{ secrets.PAT_TOKEN }}

      - name: Verify files
        run: |
          echo "Listing all files:"
          ls -R bicep-template

      - name: Show workspace location
        run: |
          Write-Host "Workspace path: $env:GITHUB_WORKSPACE"
          Get-Location
          Get-ChildItem

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          ./bicep-template/Bicep_Template/Sample.ps1
